# Generated by Django 4.2.4 on 2023-08-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='show_monthly',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='show_yearly',
        ),
    ]
