# Generated by Django 4.2.4 on 2023-08-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pricingplan_name_delete_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile Plan'), ('basic', 'Basic Plan'), ('standard', 'Standard plan'), ('premium', 'Premium Plan')], max_length=20, null=True),
        ),
    ]
