# Generated by Django 4.2.4 on 2023-08-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pricingplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile Plan'), ('basic', 'Basic Plan'), ('standard', 'Standard plan'), ('premium', 'Premium Plan')], default='mobile', max_length=20, null=True),
        ),
    ]
