# Generated by Django 4.2.4 on 2023-08-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pricingplan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='name',
            new_name='plan_name',
        ),
    ]
