# Generated by Django 4.2.4 on 2023-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_name_pricingplan_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='month_year',
            field=models.BooleanField(default=True),
        ),
    ]
